---
- name: Deploy React App Front-end Build
  connection: ssh
  gather_facts: false
  hosts: all
  vars:
    repo_folder: /var/www/mypratice
    live_folder: /var/www/ansible/ansi
    repo_name: shrutigrover96@gmail.com/mypratice
  tasks:
    - git:
        repo: ssh://git@github.com/{{ repo_name }}.git
        dest: "{{ repo_folder }}"
        update: yes
   - name: Install dependencies
      yarn:
        path: "{{ repo_folder }}"
   - name: Build project
      command: yarn build
      args:
        chdir: "{{ repo_folder }}"
    
   - name: Copy build to live directory
      command: cp -TRv build {{ live_folder }}
      args:
        chdir: "{{ repo_folder }}"
